redis:
  image: redis:alpine
  command: redis-server --requirepass redis 
  ports: ["6379"]

log-shipper:
  image: docker.elastic.co/logstash/logstash:5.4.0
  volumes:
    - ./logstash-shipper/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    - ./logstash-shipper/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./aaa.msg:/var/log/messages
  links:
    - redis:redis

log-indexer:
  image: docker.elastic.co/logstash/logstash:5.4.0
  volumes:
    - ./logstash-indexer/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    - ./logstash-indexer/logstash.yml:/usr/share/logstash/config/logstash.yml
  links:
    - redis:redis
    - elasticsearch:elasticsearch

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
  volumes:
    - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  ports:
    - 9200:9200

